package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/softwaresalt/backlogit/internal/docline"
)

// TestGenerateDocs_ProducesMarkdownFiles asserts that generateDocs creates at
// least one Markdown file in the output directory.
func TestGenerateDocs_ProducesMarkdownFiles(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err, "generateDocs should complete without error")

	entries, err := os.ReadDir(outDir)
	require.NoError(t, err)
	require.NotEmpty(t, entries, "output directory should contain at least one file")
}

// TestGenerateDocs_RootCommandPageExists asserts that the root backlogit command
// page is generated as backlogit.md.
func TestGenerateDocs_RootCommandPageExists(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err)

	rootPage := filepath.Join(outDir, "backlogit.md")
	assert.FileExists(t, rootPage, "backlogit.md should be generated as the root command reference page")
}

// TestGenerateDocs_FrontmatterPresent asserts that generated pages start with
// YAML frontmatter delimited by "---".
func TestGenerateDocs_FrontmatterPresent(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err)

	rootPage := filepath.Join(outDir, "backlogit.md")
	content, err := os.ReadFile(rootPage)
	require.NoError(t, err)

	assert.True(t, strings.HasPrefix(string(content), "---\n"),
		"generated pages must start with YAML frontmatter (---)")
}

// TestGenerateDocs_NoAutoGenTag asserts that DisableAutoGenTag = true prevents
// cobra's auto-generated disclaimer from appearing in generated files.
func TestGenerateDocs_NoAutoGenTag(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err)

	rootPage := filepath.Join(outDir, "backlogit.md")
	content, err := os.ReadFile(rootPage)
	require.NoError(t, err)

	assert.NotContains(t, string(content), "Auto generated by spf13/cobra",
		"DisableAutoGenTag must be true; auto-gen disclaimer must not appear in output")
}

// TestGenerateDocs_EmitsDoclineFrontmatter asserts that generated pages carry
// docline-conformant frontmatter (reference doc_type, repo-relative source,
// seeded ingested_at) so they are born-compliant for the CI lint gate.
func TestGenerateDocs_EmitsDoclineFrontmatter(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, generateDocs(outDir))

	raw, err := os.ReadFile(filepath.Join(outDir, "backlogit_add.md"))
	require.NoError(t, err)

	md, err := docline.Decode(raw)
	require.NoError(t, err)
	require.True(t, md.HasFrontmatter)

	b := docline.FromMap(md.Frontmatter)
	assert.Equal(t, "reference", b.DocType, "generated pages carry the reference doc_type")
	assert.Equal(t, "docs/cli-reference/backlogit_add.md", b.Source, "source is the repo-relative POSIX path")
	assert.NotEmpty(t, b.Title)
	assert.NotEmpty(t, b.IngestedAt, "ingested_at is seeded")
	assert.Equal(t, "h1-h2-h3", b.ChunkStrategy)
	assert.Equal(t, "1.0", b.SchemaVersion)

	// The generated page satisfies the authoring profile (the CI gate).
	require.NoError(t, docline.Validate(b, docline.ProfileAuthoring))
}

// TestGenerateDocs_AllPagesPassAuthoringProfile asserts that every generated
// page (README.md is hand-written and migrated separately) passes the authoring
// validation profile the CI gate enforces.
func TestGenerateDocs_AllPagesPassAuthoringProfile(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, generateDocs(outDir))

	entries, err := os.ReadDir(outDir)
	require.NoError(t, err)
	checked := 0
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".md" || e.Name() == "README.md" {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(outDir, e.Name()))
		require.NoError(t, err)
		md, err := docline.Decode(raw)
		require.NoError(t, err)
		b := docline.FromMap(md.Frontmatter)
		assert.NoErrorf(t, docline.Validate(b, docline.ProfileAuthoring),
			"page %s must satisfy the authoring profile", e.Name())
		checked++
	}
	assert.Greater(t, checked, 0, "at least one generated page must be checked")
}

// TestGenerateDocs_StableAcrossRegen asserts regeneration is byte-stable so the
// CLI-Reference-Drift check stays green: the seeded ingested_at is preserved on
// re-run instead of churning to a new timestamp.
func TestGenerateDocs_StableAcrossRegen(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, generateDocs(outDir))
	first, err := os.ReadFile(filepath.Join(outDir, "backlogit_add.md"))
	require.NoError(t, err)

	require.NoError(t, generateDocs(outDir))
	second, err := os.ReadFile(filepath.Join(outDir, "backlogit_add.md"))
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second), "regeneration must be byte-stable (no drift)")
}

// TestGenerateDocs_FrontmatterIsCanonical asserts that a docline migration over
// a generated page is a no-op: normalizing the generated bytes yields the same
// bytes, so the global migrate idempotency check and the CI gate agree with
// gen-docs and never fight it.
func TestGenerateDocs_FrontmatterIsCanonical(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, generateDocs(outDir))
	raw, err := os.ReadFile(filepath.Join(outDir, "backlogit_add.md"))
	require.NoError(t, err)

	normalized, err := docline.Normalize(
		"docs/cli-reference/backlogit_add.md", raw,
		docline.NormalizeOptions{Now: time.Now().UTC()})
	require.NoError(t, err)
	assert.Equal(t, string(raw), string(normalized),
		"generated frontmatter is already canonical (migrate no-op)")
}

func TestGenerateDocs_ComplexitySemantics(t *testing.T) {
	outDir := t.TempDir()
	require.NoError(t, generateDocs(outDir))

	updateRaw, err := os.ReadFile(filepath.Join(outDir, "backlogit_update.md"))
	require.NoError(t, err)
	listRaw, err := os.ReadFile(filepath.Join(outDir, "backlogit_list.md"))
	require.NoError(t, err)
	assert.Contains(t, string(updateRaw), "explicit empty string clears")

	for _, raw := range []string{string(updateRaw), string(listRaw)} {
		assert.Contains(t, raw, "--complexity")
		assert.Contains(t, raw, "size = implementation volume")
		assert.Contains(t, raw, "complexity = implementation difficulty and uncertainty")
		assert.Contains(t, raw, "priority = urgency")
		assert.Contains(t, raw, "Default queue ordering does not change")
	}
}
