package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestGenerateDocs_ProducesMarkdownFiles asserts that generateDocs creates at
// least one Markdown file in the output directory.
func TestGenerateDocs_ProducesMarkdownFiles(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err, "generateDocs should complete without error")

	entries, err := os.ReadDir(outDir)
	require.NoError(t, err)
	require.NotEmpty(t, entries, "output directory should contain at least one file")
}

// TestGenerateDocs_RootCommandPageExists asserts that the root backlogit command
// page is generated as backlogit.md.
func TestGenerateDocs_RootCommandPageExists(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err)

	rootPage := filepath.Join(outDir, "backlogit.md")
	assert.FileExists(t, rootPage, "backlogit.md should be generated as the root command reference page")
}

// TestGenerateDocs_NoAutoGenTag asserts that DisableAutoGenTag = true prevents
// cobra's auto-generated disclaimer from appearing in generated files.
func TestGenerateDocs_NoAutoGenTag(t *testing.T) {
	outDir := t.TempDir()

	err := generateDocs(outDir)
	require.NoError(t, err)

	rootPage := filepath.Join(outDir, "backlogit.md")
	content, err := os.ReadFile(rootPage)
	require.NoError(t, err)

	assert.NotContains(t, string(content), "Auto generated by spf13/cobra",
		"DisableAutoGenTag must be true; auto-gen disclaimer must not appear in output")
}
